version: '2'

volumes:
   my-persistent-storage:

services:
  camera-capture:
    build: ./app
    devices:
      - "/dev/video0:/dev/video0"
    restart: always
    privileged: true
    user: root
    volumes:
      -  my-persistent-storage:/app/output
